platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

project 'library-demo.xcodeproj'

def import_pods
    pod 'couchbase-lite-ios', '1.3.1'
    pod 'couchbase-lite-ios/SQLCipher', '1.3.1'
    pod 'FDKeychain', '~> 1.3'
    pod 'DDDKeychainWrapper', '~> 1.0'
end

target 'library-demo' do
    import_pods
end
